// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxTbsk43v4dyFNfWu-c6jXCRUyOHYFuVk',
    appId: '1:572817748798:web:762a72a0e265210701326f',
    messagingSenderId: '572817748798',
    projectId: 'chat-app-bb88e',
    authDomain: 'chat-app-bb88e.firebaseapp.com',
    storageBucket: 'chat-app-bb88e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOejX4_zo9v-YjY2dzzf5b5TsbQUGXA4',
    appId: '1:572817748798:android:39f24fb7b77f8eb401326f',
    messagingSenderId: '572817748798',
    projectId: 'chat-app-bb88e',
    storageBucket: 'chat-app-bb88e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsvcE0aIC7U1PVUZmXYpxG8QbIeqtLDY',
    appId: '1:572817748798:ios:f83a52e5ffe4168501326f',
    messagingSenderId: '572817748798',
    projectId: 'chat-app-bb88e',
    storageBucket: 'chat-app-bb88e.appspot.com',
    iosBundleId: 'com.example.gukgoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsvcE0aIC7U1PVUZmXYpxG8QbIeqtLDY',
    appId: '1:572817748798:ios:f83a52e5ffe4168501326f',
    messagingSenderId: '572817748798',
    projectId: 'chat-app-bb88e',
    storageBucket: 'chat-app-bb88e.appspot.com',
    iosBundleId: 'com.example.gukgoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxTbsk43v4dyFNfWu-c6jXCRUyOHYFuVk',
    appId: '1:572817748798:web:f5815b747f450ac701326f',
    messagingSenderId: '572817748798',
    projectId: 'chat-app-bb88e',
    authDomain: 'chat-app-bb88e.firebaseapp.com',
    storageBucket: 'chat-app-bb88e.appspot.com',
  );
}
